sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: SO7KyS/Qyywxo4guoz9ZT6RVT3mXxUfqhRpDPSB6REkBC0XY0o4o1G/NLwnqeR/jBNOZQm34eLm/RQWJIcS2MpnDGsAXbEjqpgIp44foaRXWRcDebCsDDR5LZmgrjS679xCnblZIf1gfVmn6pac9rw5tgMFiLJVvy3eHaNrvqdzEHyBILxcVDsuwQm61pgworRvNik0ym7u87aSir2JoHjQOCTdCARJsF+k7x+LaL8aNZlhLue8/zOaimARFOkNGJ2HZ+ueBhLWPPNTLSWxKPXBHDzuLvnrNXP5yLqIy0DYV7282Q8B9M8ggypNZPHh0mszhLYeFn5os1YcA8jgJSpNB57o4RpbaZ0bJA7J9Ilw0bnpOmr1mBLBbM/gfKC6CmAwIdBKkCNoIjN1vgsFJtR+/8xD/tAno0+MUF4P9Jz+2OifTTy7nPcQN5YiNPaNDFJw9YO6PnhqI8e3/EdYsUzrON4hffu6ysXdL8FJwoBDa0eh/F86tbPIAEK/w7sAvYvpcDdUG4dAExrHoWae2g402sFwFVG6xNsvmcjOlT01g/e8KD7XwaMZs84kjjbVXk4s4m7x3R9FR8fGIOhFyi2BjGxRhBtgXSHhSWd+8qtiuCsh1FOWh4WBWKlioGTrCrben1cEvrvIhqVpWS9wchxNrXBXKdEKEnRngIu90EEI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Widger-s-Quotations-from-the-Project-Gutenberg-Editions-of-the-Works-of-Oliver-W-Holmes-Sr_3493
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy